// 生成小程序图标字体样式（Bootstrap Icons 子集，base64 内嵌 woff2）。
// 读取 node_modules/bootstrap-icons 的码点 JSON + woff2，输出 src/styles/icons.gen.scss。
// 用法：node scripts/gen-icons.mjs
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const jsonPath = join(root, 'node_modules/bootstrap-icons/font/bootstrap-icons.json')
const woff2Path = join(root, 'node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2')

if (!existsSync(jsonPath) || !existsSync(woff2Path)) {
  console.error('未找到 bootstrap-icons 字体文件，请先 npm i -D bootstrap-icons')
  process.exit(1)
}

const codepoints = JSON.parse(readFileSync(jsonPath, 'utf8'))
const woff2 = readFileSync(woff2Path)
const base64 = woff2.toString('base64')

// 所需图标子集（按页面归类，缺失的会自动跳过并警告）
const ICONS = [
  // 通用
  'check-circle', 'info-circle', 'exclamation-triangle', 'x-circle', 'x-lg',
  'chevron-down', 'chevron-up', 'chevron-right', 'chevron-left', 'arrow-right',
  'plus-lg', 'trash', 'download', 'copy', 'check', 'search',
  // 概览
  'grid', 'chat-dots', 'gear', 'stars', 'shield-check', 'lightning-charge',
  'layers', 'calendar3', 'clock-history',
  // 排盘
  'moon-stars', 'sun-fill', 'flower1', 'journal-text', 'send', 'stop-circle',
  'arrow-repeat', 'magic', 'clipboard-data', 'person-badge',
  // 对话
  'robot', 'person', 'send-plus',
  // 设置
  'key-fill', 'plug-fill', 'plug', 'database', 'palette', 'display', 'pencil',
  'shield-lock', 'sliders', 'wifi', 'cpu', 'file-earmark-text', 'cloud-arrow-up'
]

const lines = []
lines.push('// AUTO-GENERATED by scripts/gen-icons.mjs — 请勿手动编辑')
lines.push('// 重新生成：node scripts/gen-icons.mjs')
lines.push('')
lines.push("// Bootstrap Icons (MIT) — woff2 base64 内嵌（微信小程序 @font-face 仅支持 data URI / 网络域名）")
lines.push('@font-face {')
lines.push("  font-family: 'bi-font';")
lines.push(`  src: url(data:font/woff2;base64,${base64}) format('woff2');`)
lines.push('}')
lines.push('')
lines.push('.icon {')
lines.push("  font-family: 'bi-font';")
lines.push('  display: inline-flex;')
lines.push('  align-items: center;')
lines.push('  justify-content: center;')
lines.push('  font-style: normal;')
lines.push('  font-weight: normal;')
lines.push('  font-size: 32px;')
lines.push('  line-height: 1;')
lines.push('  vertical-align: middle;')
lines.push('}')
lines.push('')

let count = 0
const missing = []
for (const name of ICONS) {
  const cp = codepoints[name]
  if (!cp) {
    missing.push(name)
    continue
  }
  lines.push(`.icon-${name}::before { content: "\\${cp}"; }`)
  count++
}
if (missing.length > 0) {
  console.warn(`⚠ 跳过缺失图标（${missing.length}）: ${missing.join(', ')}`)
}

const dest = join(root, 'src', 'styles', 'icons.gen.scss')
mkdirSync(dirname(dest), { recursive: true })
writeFileSync(dest, lines.join('\n') + '\n', 'utf8')
console.log(`✓ 已生成 ${dest}（${count} 个图标，字体 base64 ${(base64.length / 1024).toFixed(0)} KB）`)
