// 生成小程序端内置技能的 TS 常量模块（替代 Vite 的 import.meta.glob）。
// 读取 src/skills/builtin/*/SKILL.md 与 references/*.md，输出 src/skills/builtin/skills.gen.ts。
// 用法：node scripts/gen-skills.mjs
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'skills', 'builtin')

const entries = readdirSync(root, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((name) => existsSync(join(root, name, 'SKILL.md')))

const out = entries.map((id) => {
  const skillDir = join(root, id)
  const content = readFileSync(join(skillDir, 'SKILL.md'), 'utf8')
  const refDir = join(skillDir, 'references')
  const references = existsSync(refDir)
    ? readdirSync(refDir)
        .filter((f) => f.endsWith('.md'))
        .map((f) => ({ name: f, content: readFileSync(join(refDir, f), 'utf8') }))
    : []
  return { id, content, references }
})

const ts = `// AUTO-GENERATED by scripts/gen-skills.mjs — 请勿手动编辑
// 重新生成：node scripts/gen-skills.mjs

export interface BuiltinSkillRaw {
  id: string
  content: string
  references: { name: string; content: string }[]
}

export const BUILTIN_SKILLS_RAW: BuiltinSkillRaw[] = ${JSON.stringify(out, null, 2)}
`

const dest = join(root, 'skills.gen.ts')
writeFileSync(dest, ts, 'utf8')
console.log(`已生成 ${dest}（${out.length} 个内置技能）`)
